baseURL = 'https://fyan1024.github.io'
languageCode = 'zh-CN'
title = 'Fyans new Hugo Site'
theme = 'hugo-theme-relearn'


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

          